<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Clear_DateofBirth</name>
   <tag></tag>
   <elementGuidId>12d32055-e8b0-443d-ab88-e5ae28bff549</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dateOfBirthInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dateOfBirthInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e1902c2-f7de-48d1-a0f4-399531fdfa0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1e12d8f2-ab28-4911-a4f2-e773a1083b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dateOfBirthInput</value>
      <webElementGuid>bd9e6f39-3e29-4c06-8bad-8641cfd24cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>bc6affd3-1b73-486f-9d3f-cc46bf0797ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>29 Nov 2025</value>
      <webElementGuid>62eab5dc-ead4-43ef-b85f-329293757f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateOfBirthInput&quot;)</value>
      <webElementGuid>de9f0ac8-8a06-4bbb-b971-636d6564a537</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dateOfBirthInput']</value>
      <webElementGuid>d6151123-3397-4f5f-8750-ec286d279353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dateOfBirth']/div/div/input</value>
      <webElementGuid>3b6e5c0b-69e4-4816-bd68-d56d7a1c96a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>c14bb8aa-c4b4-4a0f-90e1-72e910fa61dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dateOfBirthInput']</value>
      <webElementGuid>caf1e8d4-d795-428e-bcf6-f4258970436a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
