<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Elements_close-fixedban</name>
   <tag></tag>
   <elementGuidId>190474a0-3580-4a65-b655-5617b6244d19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#close-fixedban</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='close-fixedban']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#close-fixedban</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d7e805eb-3ae7-43cd-8ab7-dfec690d6ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close-fixedban</value>
      <webElementGuid>db061ae2-7836-4905-80e3-fd0ba6a8400f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>document.getElementById(&quot;fixedban&amp;apos&quot;).style.display=&quot;none&amp;apos&quot;</value>
      <webElementGuid>821af657-5714-44f4-a18c-a29c5d3514dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-fixedban&quot;)</value>
      <webElementGuid>20e48aee-cabb-4894-9dce-e0ff0aa6a123</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='close-fixedban']</value>
      <webElementGuid>2b2a0779-e5ac-41c7-8fd7-3225579c595d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fixedban']/div/div/a</value>
      <webElementGuid>4b279d25-e763-4c56-b45e-e9ce420905c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elements'])[1]/preceding::a[2]</value>
      <webElementGuid>595e8b7a-be93-4cb8-b131-20924a8ae91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Text Box'])[1]/preceding::a[2]</value>
      <webElementGuid>a4cab9d6-e2c1-42ed-86d6-1ceafea38a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>94cf5549-6578-4787-bd45-6e9956656329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'close-fixedban']</value>
      <webElementGuid>18a86bb2-1e78-4304-a9f6-eca9009b8c43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
